## Import Packages

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Import Data

In [2]:
gen_polls = pd.read_csv("../datasets/president_polls.csv")
dem_platform = pd.read_csv("../datasets/US-Party-Dem_Platform_19.2.csv")
rep_platform = pd.read_csv("../datasets/US-Party-Rep_Platform_19.2..csv")

### General Presidential

In [3]:
gen_polls.shape

(2399, 36)

In [4]:
gen_polls.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2399 entries, 0 to 2398
Data columns (total 36 columns):
question_id                  2399 non-null int64
poll_id                      2399 non-null int64
cycle                        2399 non-null int64
state                        1227 non-null object
pollster_id                  2399 non-null int64
pollster                     2399 non-null object
sponsor_ids                  914 non-null object
sponsors                     914 non-null object
display_name                 2399 non-null object
pollster_rating_id           2399 non-null int64
pollster_rating_name         2399 non-null object
fte_grade                    2251 non-null object
sample_size                  2399 non-null int64
population                   2399 non-null object
population_full              2399 non-null object
methodology                  2397 non-null object
office_type                  2399 non-null object
seat_number                  2399 non-null int64
seat_name                    0 non-null float64
start_date                   2399 non-null object
end_date                     2399 non-null object
election_date                126 non-null object
sponsor_candidate            8 non-null object
internal                     2399 non-null bool
partisan                     27 non-null object
tracking                     0 non-null float64
nationwide_batch             2399 non-null bool
ranked_choice_reallocated    2399 non-null bool
created_at                   2399 non-null object
notes                        48 non-null object
url                          2399 non-null object
stage                        2399 non-null object
answer                       2399 non-null object
candidate_name               2399 non-null object
candidate_party              2399 non-null object
pct                          2399 non-null float64
dtypes: bool(3), float64(3), int64(7), object(23)
memory usage: 625.6+ KB

In [5]:
gen_polls.sample(5)

,question_id,poll_id,cycle,state,pollster_id,pollster,sponsor_ids,sponsors,display_name,pollster_rating_id,...,nationwide_batch,ranked_choice_reallocated,created_at,notes,url,stage,answer,candidate_name,candidate_party,pct
441,111155,62228,2020,California,460,SurveyUSA,"443,583,804",KGTV-TV (California) | KABC-TV (California) | ...,SurveyUSA,325,...,False,False,10/22/19 22:00,NaN,http://www.surveyusa.com/client/PollReport.asp...,general,Pence,Mike Pence,REP,30.0
2223,93284,57574,2020,New Hampshire,1102,Emerson College,NaN,NaN,Emerson College,88,...,False,False,2/23/19 13:40,NaN,http://emersonpolling.com/2019/02/23/bernie-ta...,general,Booker,Cory A. Booker,DEM,50.9
1056,100770,58930,2020,Colorado,1102,Emerson College,NaN,NaN,Emerson College,88,...,False,False,8/20/19 08:31,NaN,http://emersonpolling.com/2019/08/20/colorado-...,general,Buttigieg,Pete Buttigieg,DEM,54.7
597,111091,59899,2020,NaN,573,Zogby Interactive/JZ Analytics,NaN,NaN,Zogby Analytics,395,...,False,False,10/21/19 19:51,NaN,https://zogbyanalytics.com/news/906-the-zogby-...,general,Trump,Donald Trump,REP,46.0
1350,99487,58695,2020,NaN,399,Rasmussen Reports/Pulse Opinion Research,NaN,NaN,Rasmussen Reports/Pulse Opinion Research,277,...,False,False,7/19/19 10:26,fielded from July 7-11 and July 14-18,http://www.rasmussenreports.com/public_content...,general,Castro,Julián Castro,DEM,40.0

### Democratic Platform 1948-2016

In [6]:
dem_platform.shape

(15953, 9)

In [7]:
dem_platform.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15953 entries, 0 to 15952
Data columns (total 9 columns):
year               15953 non-null int64
id                 15953 non-null int64
pap_majortopic     15953 non-null int64
pap_subtopic       15953 non-null int64
majortopic         15953 non-null int64
subtopic           15953 non-null int64
description        15953 non-null object
filter_democrat    15953 non-null int64
words              15953 non-null int64
dtypes: int64(8), object(1)
memory usage: 1.1+ MB

In [8]:
dem_platform.sample(5)

,year,id,pap_majortopic,pap_subtopic,majortopic,subtopic,description,filter_democrat,words
2156,1964,2118,19,1929,19,1929,Nine thousand have served in a total of 45 cou...,1,10
5288,1976,5253,4,402,4,402,revitalize basic credit programs for farmers;,1,6
4143,1972,4107,13,1301,13,1302,Continue with full federal funding the breakfa...,1,22
14091,2012,14085,0,-555,0,-555,Strengthening the American Community,1,4
2392,1964,2354,4,400,4,400,"In 1960, we said√≠√Ø""In every way we will seek...",1,33

### Republican Platform 1948-2016

In [9]:
rep_platform.shape

(19836, 8)

In [10]:
rep_platform.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19836 entries, 0 to 19835
Data columns (total 8 columns):
year              19836 non-null int64
id                19836 non-null int64
pap_majortopic    19836 non-null int64
pap_subtopic      19836 non-null int64
majortopic        19836 non-null int64
subtopic          19836 non-null int64
description       19836 non-null object
words             19836 non-null int64
dtypes: int64(7), object(1)
memory usage: 1.2+ MB

In [11]:
rep_platform.sample(5)

,year,id,pap_majortopic,pap_subtopic,majortopic,subtopic,description,words
9617,1992,9543,6,607,6,607,that American children should be first in the ...,13
398,1952,310,4,498,4,498,We recommend expanded agricultural research an...,42
4421,1976,4340,4,401,4,401,We shall not permit concessional sales of agri...,33
8078,1988,8001,14,1409,14,1409,[p.31] ¬å¬´√≠_√≠_√≠_√≠_√≠_√≠_√≠_√≠_√≠_√≠_√≠_ W...,16
5066,1980,4987,1,100,1,100,Republicans are committed to an economic polic...,19

In [12]:
rep_platform.loc[rep_platform["year"] > 1950]

,year,id,pap_majortopic,pap_subtopic,majortopic,subtopic,description,words
0,1976,3740,2,202,2,202,a position on abortion that values human life;,8
1,1976,3823,2,202,2,202,The question of abortion is one of the most di...,15
2,1976,3825,2,202,2,202,There are those in our Party who favor complet...,20
3,1976,3826,2,202,2,202,There are others who share sincere convictions...,22
4,1976,3829,2,202,2,202,The Republican Party favors a continuance of t...,36
...,...,...,...,...,...,...,...,...
19831,2016,19832,19,1925,19,1925,Internet firewall circumvention and anti-censo...,37
19832,2016,19833,19,1925,19,1925,Leaders of authoritarian governments argue tha...,23
19833,2016,19834,19,1925,19,1925,A focus on internet freedom is a cost-effectiv...,19
19834,2016,19835,18,1803,18,1803,"But it is also an important economic interest,...",27
19835,2016,19836,19,1929,19,1929,A Republican administration will champion an o...,44