# Import Packages

In [1]:
import pandas as pd

# Get Data

In [2]:
state_hist = pd.read_csv("datasets/1976-2016-president.csv")
polls = pd.read_csv("datasets/president_polls.csv")

## Data Cleaning

In [3]:
# Get the results from the last 7 election cycles and only with major party candidates
recent_elec = state_hist.loc[(state_hist["party"] == "democrat") | (state_hist["party"] == "republican")].loc[state_hist["year"] >= 1992]

# Reset the index of the new DataFrame
recent_elec.index = range(0, len(recent_elec.index))

In [4]:
# Remove write-in candidates
recent_elec = recent_elec.loc[recent_elec["writein"] == False]

In [5]:
# Minnesota is missing results in 3 cases
recent_elec["state"].value_counts()

New York                14
District of Columbia    14
Delaware                14
West Virginia           14
Virginia                14
Arkansas                14
Michigan                14
Kentucky                14
Vermont                 14
Idaho                   14
North Dakota            14
Utah                    14
Illinois                14
South Dakota            14
Texas                   14
New Jersey              14
Colorado                14
Hawaii                  14
Oregon                  14
California              14
Alaska                  14
Montana                 14
Oklahoma                14
North Carolina          14
Wyoming                 14
Washington              14
Massachusetts           14
South Carolina          14
Florida                 14
Kansas                  14
Louisiana               14
Missouri                14
Alabama                 14
Connecticut             14
Maine                   14
Indiana                 14
Pennsylvania            14
New Mexico              14
Tennessee               14
Wisconsin               14
Nevada                  14
New Hampshire           14
Georgia                 14
Iowa                    14
Mississippi             14
Nebraska                14
Maryland                14
Rhode Island            14
Ohio                    14
Arizona                 14
Minnesota               11
Name: state, dtype: int64

In [6]:
# 2012, 2004, 2000 elections have one row and only outline the republican candidate.
# Minnesota voted Democratic the last 7 presidential cycles, making note to fix later.
recent_elec.loc[recent_elec["state"] == "Minnesota"]

,year,state,state_po,state_fips,state_cen,state_ic,office,candidate,party,writein,candidatevotes,totalvotes,version,notes
46,1992,Minnesota,MN,27,41,33,US President,"Clinton, Bill",democrat,False,1020997,2347948,20171015,NaN
47,1992,Minnesota,MN,27,41,33,US President,"Bush, George H.W.",republican,False,747841,2347948,20171015,NaN
148,1996,Minnesota,MN,27,41,33,US President,"Clinton, Bill",democrat,False,1120380,2192492,20171015,NaN
149,1996,Minnesota,MN,27,41,33,US President,"Dole, Robert",republican,False,766395,2192492,20171015,NaN
250,2000,Minnesota,MN,27,41,33,US President,"Bush, George W.",republican,False,1109659,2438685,20171015,NaN
352,2004,Minnesota,MN,27,41,33,US President,"Bush, George W.",republican,False,1346695,2828387,20171015,NaN
453,2008,Minnesota,MN,27,41,33,US President,"Obama, Barack H.",democrat,False,1573354,2910369,20171015,NaN
454,2008,Minnesota,MN,27,41,33,US President,"McCain, John",republican,False,1275409,2910369,20171015,NaN
555,2012,Minnesota,MN,27,41,33,US President,"Romney, Mitt",republican,False,1320225,2936561,20171015,NaN
659,2016,Minnesota,MN,27,41,33,US President,"Clinton, Hillary",democrat,False,1367705,2944782,20171015,NaN
660,2016,Minnesota,MN,27,41,33,US President,"Trump, Donald J.",republican,False,1322949,2944782,20171015,NaN

In [7]:
# Create a new DataFrame with the party of the candidate receiving the electoral votes for eacher year by state
vote_list = []
for i in recent_elec[["year", "state"]].values:
    state_year = recent_elec.loc[(recent_elec["state"] == i[1]) & (recent_elec["year"] == i[0])]
    party_val = state_year.sort_values("candidatevotes", ascending = False).reset_index(drop = True)["party"][0]

    state_party = [i[0], i[1], party_val]
    if state_party not in vote_list:
        vote_list.append(state_party)

In [8]:
# Create DataFrame separating the year, state, and vote result
election_results = pd.DataFrame(vote_list, columns = ["year", "state", "vote"])

In [9]:
# Transform the DataFrame to have columns of year and index of state
votes_by_year = pd.DataFrame(election_results["year"].unique(),columns = ["year"])
for state in election_results["state"].unique():
    votes_by_year[state] = election_results.loc[election_results["state"] == state, "vote"].values

In [10]:
# Fix the Minnesota results to reflect the 2012, 2004, and 2000 voting results.
# We expect to see Democrat, but see Republican.
votes_by_year["Minnesota"] = "democrat"

In [11]:
# Map 0 and 1 values onto values of republican and democrat
for state in votes_by_year.drop("year", axis = 1):
    votes_by_year[state] = votes_by_year[state].map({"republican": 0, "democrat": 1})

In [12]:
votes_by_year.to_csv("datasets/historic_voting.csv")

## Create Correlation DataFrame for Past Voting Behavior

In [13]:
# Get a correlation DF between state voting records
corr_df = votes_by_year.drop("year", axis = 1).corr()

# Drop columns and rows with states that have voted with one party last 7 cycles
corr_df = corr_df.dropna(axis = 1, how = "all").dropna(axis = 0, how = "all")

# States with polls that haven't voted consistently the last 10 cycles
for i in polls["state"].unique():
    if i in corr_df.columns:
        print(i)

New Hampshire
Georgia
Wisconsin
North Carolina
Nevada
Pennsylvania
Michigan
Iowa
Arizona
Florida
Ohio
Virginia
Montana
Missouri
Colorado
Kentucky

In [14]:
corr_df.head()

,Arizona,Arkansas,Colorado,Florida,Georgia,Indiana,Iowa,Kentucky,Louisiana,Michigan,...,Nevada,New Hampshire,New Mexico,North Carolina,Ohio,Pennsylvania,Tennessee,Virginia,West Virginia,Wisconsin
Arizona,1.000000,0.645497,-0.471405,0.471405,-0.166667,-0.166667,0.258199,0.645497,0.645497,0.166667,...,0.258199,0.166667,0.166667,-0.166667,0.353553,0.166667,0.645497,-0.353553,0.645497,0.166667
Arkansas,0.645497,1.000000,-0.091287,0.091287,0.645497,-0.258199,0.400000,1.000000,1.000000,0.258199,...,0.400000,0.258199,0.258199,-0.258199,0.547723,0.258199,1.000000,-0.547723,1.000000,0.258199
Colorado,-0.471405,-0.091287,1.000000,0.166667,0.353553,0.353553,0.091287,-0.091287,-0.091287,-0.353553,...,0.730297,0.471405,0.471405,0.353553,0.416667,-0.353553,-0.091287,0.750000,-0.091287,-0.353553
Florida,0.471405,0.091287,0.166667,1.000000,-0.353553,0.471405,0.547723,0.091287,0.091287,0.353553,...,0.547723,0.353553,0.353553,0.471405,0.750000,0.353553,0.091287,0.416667,0.091287,0.353553
Georgia,-0.166667,0.645497,0.353553,-0.353553,1.000000,-0.166667,0.258199,0.645497,0.645497,0.166667,...,0.258199,0.166667,0.166667,-0.166667,0.353553,0.166667,0.645497,-0.353553,0.645497,0.166667

In [15]:
corr_df.to_csv("datasets/statewide_correlation.csv", header = False)